plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.seleva'
version = '0.0.1'

android {
  namespace 'expo.modules.seleva'
  defaultConfig {
    versionCode 1
    versionName '0.0.1'
  }
}

dependencies {
  implementation 'com.google.mlkit:text-recognition:16.0.1'
  testImplementation 'junit:junit:4.13.2'
}
